name: ahangoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  go_router: ^14.2.7
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  fluttertoast: ^8.2.8
  awesome_snackbar_content: ^0.1.4
  logger: ^2.4.0
  flutter_router: ^1.2.0
  curved_labeled_navigation_bar: ^2.0.2
  flutter_svg: ^2.0.10+1
  flutter_carousel_widget: ^3.0.1
  google_maps_flutter: ^2.9.0
  flutter_tts: ^4.0.2
  path_provider: ^2.1.4
  timeline_tile: ^2.0.0
  timelines_plus: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/svgs/
